FROM alpine:latest

RUN apk add --no-cache ca-certificates tzdata

COPY edgelink-server /usr/local/bin/edgelink-server

RUN chmod +x /usr/local/bin/edgelink-server

EXPOSE 8081 3478/udp

ENTRYPOINT ["/usr/local/bin/edgelink-server"]
CMD ["-c", "/etc/edgelink/server.json"]
